import type { Accessory, Product } from "./types";

const defaultConfigurator = {
  colors: [
    { id: "midnight", name: "Midnight Black", hex: "#0a0a0a" },
    { id: "alpine", name: "Alpine White", hex: "#f5f5f5" },
    { id: "bavarian", name: "Bavarian Blue", hex: "#1e3a5f" },
    { id: "forest", name: "Forest Green", hex: "#1a2e1a" },
  ],
  wheels: [
    { id: "standard", name: "18\" Standard", price: 0 },
    { id: "sport", name: "20\" Sport Alloy", price: 890 },
    { id: "offroad", name: "21\" Off-Road", price: 1290 },
  ],
  battery: [
    { id: "standard", name: "Standard", range: "180 km", price: 0 },
    { id: "extended", name: "Extended Range", range: "280 km", price: 3490 },
    { id: "performance", name: "Performance", range: "320 km", price: 5490 },
  ],
  roof: [
    { id: "solid", name: "Solid Roof", price: 0 },
    { id: "panoramic", name: "Panoramic Glass", price: 1890 },
    { id: "solar", name: "Solar Roof", price: 2490 },
  ],
  cargoBox: [
    { id: "none", name: "No Cargo Box", price: 0 },
    { id: "compact", name: "Compact Box", price: 690 },
    { id: "max", name: "Max Cargo", price: 1190 },
  ],
};

export const products: Product[] = [
  {
    id: "volt-x1",
    slug: "volt-x1",
    name: "Volt X1",
    tagline: "The urban revolution",
    description:
      "Our flagship electric utility vehicle. Precision engineered for European roads, designed for those who refuse to compromise.",
    price: 24990,
    category: "Electric Utility Vehicles",
    categoryId: "utility",
    badge: "premium",
    availability: "in-stock",
    brand: "eRide Bavaria",
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1600&q=80",
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1600&q=80",
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=1600&q=80",
    ],
    specs: {
      battery: "72 kWh",
      batteryKwh: 72,
      power: "120 kW",
      powerKw: 120,
      charging: "35 min",
      range: "220 km",
      rangeKm: 220,
      topSpeed: "95 km/h",
      topSpeedKmh: 95,
      payload: "450 kg",
      payloadKg: 450,
      seats: 2,
      dimensions: "3.2 × 1.4 × 1.8 m",
      weight: "680 kg",
      weightKg: 680,
      motor: "Dual Motor AWD",
    },
    story: [
      {
        title: "Born in Bavaria",
        text: "Every curve, every line, every component — engineered in our Munich facility with uncompromising attention to detail.",
        image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=1400&q=80",
      },
      {
        title: "Silent Power",
        text: "Dual motor all-wheel drive delivers instant torque without a sound. Move through the city. Move through nature. Move without leaving a trace.",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=80",
      },
      {
        title: "Built to Last",
        text: "Premium materials. European safety standards. A vehicle designed not for seasons, but for decades.",
        image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1400&q=80",
      },
    ],
    configurator: defaultConfigurator,
    relatedAccessoryIds: ["magnetic-charger", "smart-display", "all-weather-cover"],
  },
  {
    id: "terra-pro",
    slug: "terra-pro",
    name: "Terra Pro",
    tagline: "Off-road electric",
    description: "Conquer any terrain with whisper-quiet electric power. Built for adventure, certified for Europe.",
    price: 18490,
    category: "Quads",
    categoryId: "quads",
    badge: "popular",
    availability: "in-stock",
    brand: "eRide Bavaria",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1600&q=80",
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1600&q=80",
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1600&q=80",
    ],
    specs: {
      battery: "48 kWh",
      batteryKwh: 48,
      power: "80 kW",
      powerKw: 80,
      charging: "45 min",
      range: "180 km",
      rangeKm: 180,
      topSpeed: "75 km/h",
      topSpeedKmh: 75,
      payload: "200 kg",
      payloadKg: 200,
      seats: 2,
      dimensions: "2.4 × 1.3 × 1.5 m",
      weight: "420 kg",
      weightKg: 420,
      motor: "Single Motor 4WD",
    },
    story: [
      {
        title: "Beyond the Pavement",
        text: "Where roads end, Terra Pro begins. All-terrain suspension meets electric precision.",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1400&q=80",
      },
    ],
    configurator: defaultConfigurator,
    relatedAccessoryIds: ["carbon-helmet", "all-weather-cover"],
  },
  {
    id: "swift-s2",
    slug: "swift-s2",
    name: "Swift S2",
    tagline: "City mobility",
    description: "The definitive urban electric scooter. Lightweight, powerful, impossibly refined.",
    price: 1290,
    category: "Scooters",
    categoryId: "scooters",
    badge: "new",
    availability: "in-stock",
    brand: "eRide Bavaria",
    images: [
      "https://images.unsplash.com/photo-1571068316347-75bc76f77890?w=1600&q=80",
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1600&q=80",
    ],
    specs: {
      battery: "1.2 kWh",
      batteryKwh: 1.2,
      power: "0.8 kW",
      powerKw: 0.8,
      charging: "4 hours",
      range: "65 km",
      rangeKm: 65,
      topSpeed: "25 km/h",
      topSpeedKmh: 25,
      payload: "120 kg",
      payloadKg: 120,
      seats: 1,
      dimensions: "1.1 × 0.45 × 1.2 m",
      weight: "14 kg",
      weightKg: 14,
      motor: "Hub Motor",
    },
    story: [
      {
        title: "The Last Mile, Reimagined",
        text: "Fold. Carry. Ride. Swift S2 transforms how you move through the city.",
        image: "https://images.unsplash.com/photo-1571068316347-75bc76f77890?w=1400&q=80",
      },
    ],
    configurator: {
      ...defaultConfigurator,
      wheels: [{ id: "standard", name: "10\" Urban", price: 0 }],
      battery: [
        { id: "standard", name: "Standard", range: "45 km", price: 0 },
        { id: "extended", name: "Extended", range: "65 km", price: 199 },
      ],
      roof: [{ id: "none", name: "N/A", price: 0 }],
      cargoBox: [{ id: "none", name: "N/A", price: 0 }],
    },
    relatedAccessoryIds: ["carbon-helmet", "magnetic-charger"],
  },
  {
    id: "cargo-e",
    slug: "cargo-e",
    name: "Cargo E",
    tagline: "Commercial grade",
    description: "Enterprise electric logistics. Zero emissions. Maximum payload. Built for business.",
    price: 32500,
    category: "Electric Utility Vehicles",
    categoryId: "utility",
    badge: "limited",
    availability: "pre-order",
    brand: "eRide Bavaria",
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1600&q=80",
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1600&q=80",
    ],
    specs: {
      battery: "96 kWh",
      batteryKwh: 96,
      power: "150 kW",
      powerKw: 150,
      charging: "40 min",
      range: "250 km",
      rangeKm: 250,
      topSpeed: "80 km/h",
      topSpeedKmh: 80,
      payload: "800 kg",
      payloadKg: 800,
      seats: 2,
      dimensions: "4.2 × 1.8 × 2.1 m",
      weight: "1200 kg",
      weightKg: 1200,
      motor: "Dual Motor AWD",
    },
    story: [
      {
        title: "Business, Electrified",
        text: "The future of last-mile delivery is silent, efficient, and unmistakably premium.",
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1400&q=80",
      },
    ],
    configurator: defaultConfigurator,
    relatedAccessoryIds: ["smart-display", "magnetic-charger"],
  },
  {
    id: "mini-drive",
    slug: "mini-drive",
    name: "Mini Drive",
    tagline: "For young explorers",
    description: "Safe, fun, electric mobility for the next generation. Parent-controlled speed limits.",
    price: 890,
    category: "Kids Vehicles",
    categoryId: "kids",
    badge: "popular",
    availability: "in-stock",
    brand: "eRide Bavaria",
    images: [
      "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=1600&q=80",
    ],
    specs: {
      battery: "0.5 kWh",
      batteryKwh: 0.5,
      power: "0.3 kW",
      powerKw: 0.3,
      charging: "3 hours",
      range: "25 km",
      rangeKm: 25,
      topSpeed: "8 km/h",
      topSpeedKmh: 8,
      payload: "50 kg",
      payloadKg: 50,
      seats: 1,
      dimensions: "1.0 × 0.6 × 0.7 m",
      weight: "28 kg",
      weightKg: 28,
      motor: "Brushless DC",
    },
    story: [
      {
        title: "First Adventures",
        text: "Every journey starts somewhere. Mini Drive makes the first one unforgettable.",
        image: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=1400&q=80",
      },
    ],
    configurator: {
      colors: [
        { id: "red", name: "Racing Red", hex: "#cc2222" },
        { id: "blue", name: "Sky Blue", hex: "#2266cc" },
        { id: "yellow", name: "Sunshine", hex: "#ccaa22" },
      ],
      wheels: [{ id: "standard", name: "All-Terrain", price: 0 }],
      battery: [{ id: "standard", name: "Standard", range: "25 km", price: 0 }],
      roof: [{ id: "none", name: "N/A", price: 0 }],
      cargoBox: [{ id: "none", name: "N/A", price: 0 }],
    },
    relatedAccessoryIds: ["carbon-helmet"],
  },
  {
    id: "urban-e",
    slug: "urban-e",
    name: "Urban E",
    tagline: "City redefined",
    description: "Compact electric car for modern urban living. Park anywhere. Go everywhere.",
    price: 34990,
    category: "Electric Cars",
    categoryId: "cars",
    badge: "new",
    availability: "in-stock",
    brand: "eRide Bavaria",
    images: [
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1600&q=80",
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1600&q=80",
    ],
    specs: {
      battery: "58 kWh",
      batteryKwh: 58,
      power: "100 kW",
      powerKw: 100,
      charging: "30 min",
      range: "310 km",
      rangeKm: 310,
      topSpeed: "130 km/h",
      topSpeedKmh: 130,
      payload: "350 kg",
      payloadKg: 350,
      seats: 4,
      dimensions: "3.8 × 1.7 × 1.5 m",
      weight: "1450 kg",
      weightKg: 1450,
      motor: "Single Motor RWD",
    },
    story: [
      {
        title: "The City is Yours",
        text: "Urban E was designed from the ground up for European cities. Tight corners. Narrow streets. Infinite possibility.",
        image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1400&q=80",
      },
    ],
    configurator: defaultConfigurator,
    relatedAccessoryIds: ["magnetic-charger", "smart-display", "all-weather-cover"],
  },
];

export const accessoryCatalog: Accessory[] = [
  {
    id: "magnetic-charger",
    slug: "magnetic-charger",
    name: "Magnetic Charger",
    price: 349,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
    description: "Snap-on magnetic charging dock with LED status.",
  },
  {
    id: "carbon-helmet",
    slug: "carbon-helmet",
    name: "Carbon Helmet",
    price: 189,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80",
    description: "Ultra-light carbon fiber with integrated LED.",
  },
  {
    id: "all-weather-cover",
    slug: "all-weather-cover",
    name: "All-Weather Cover",
    price: 129,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80",
    description: "Breathable, waterproof protection for any season.",
  },
  {
    id: "smart-display",
    slug: "smart-display",
    name: "Smart Display",
    price: 449,
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&q=80",
    description: "10\" touchscreen with navigation and diagnostics.",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getAccessoryById(id: string): Accessory | undefined {
  return accessoryCatalog.find((a) => a.id === id);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("de-DE", {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: 0,
  }).format(price);
}

export const trendingSearches = [
  "Volt X1",
  "Urban E",
  "Electric Scooter",
  "Cargo E",
  "Charger",
];

export const compareSpecKeys = [
  { key: "rangeKm", label: "Range", format: (p: Product) => p.specs.range },
  { key: "powerKw", label: "Power", format: (p: Product) => p.specs.power },
  { key: "batteryKwh", label: "Battery", format: (p: Product) => p.specs.battery },
  { key: "topSpeedKmh", label: "Top Speed", format: (p: Product) => p.specs.topSpeed },
  { key: "weightKg", label: "Weight", format: (p: Product) => p.specs.weight },
  { key: "payloadKg", label: "Payload", format: (p: Product) => p.specs.payload },
  { key: "seats", label: "Seats", format: (p: Product) => String(p.specs.seats) },
  { key: "charging", label: "Charging", format: (p: Product) => p.specs.charging },
  { key: "motor", label: "Motor", format: (p: Product) => p.specs.motor },
] as const;
