export const showroomLabels = {
  intro: "Digitales Showroom",
  configure: "Konfigurieren",
  explore: "Erkunden",
  modes: {
    showroom: "Showroom",
    exploded: "Explosionsansicht",
    parts: "Ersatzteile",
    compare: "Vergleich",
  },
  views: {
    exterior: "Außen",
    interior: "Innenraum",
    cargo: "Ladefläche",
    underside: "Unterboden",
    battery: "Batterie",
    lighting: "Beleuchtung",
  },
  rotate: "Ziehen zum Drehen",
  zoom: "Scrollen zum Zoomen",
  hotspot: "Detail erkunden",
  addToCart: "Konfiguration sichern",
  reserve: "Reservieren",
  priceFrom: "ab",
  delivery: "Lieferzeit",
  weeks: "Wochen",
  range: "Reichweite",
  weight: "Gewicht",
  payload: "Zuladung",
  configuration: "Deine Konfiguration",
  configuredPrice: "Konfigurierter Preis",
  saveConfig: "Konfiguration speichern",
  compareConfigs: "Konfigurationen vergleichen",
  configA: "Aktuelle Konfiguration",
  configB: "Gespeicherte Konfiguration",
  diff: "Unterschiede",
  partsLibrary: "Teilekatalog",
  searchParts: "Teile suchen…",
  originalPart: "Original-Ersatzteil",
  installDifficulty: "Einbau",
  installTime: "Einbauzeit",
  deliveryTime: "Lieferzeit",
  days: "Tage",
  compatibility: "Kompatibilität",
  technicalDrawing: "Technische Zeichnung",
  aiTitle: "KI-Teileerkennung",
  aiSubtitle: "Lade ein Foto des beschädigten Bauteils hoch",
  aiUpload: "Bild hochladen",
  aiAnalyzing: "Analysiere Bauteil…",
  aiResult: "Erkanntes Bauteil",
  aiConfidence: "Übereinstimmung",
  aiTools: "Benötigte Werkzeuge",
  aiMaintenance: "Wartungsempfehlung",
  aiHighlight: "Position im Fahrzeug",
  accessories: "Zubehör",
  attachAccessory: "Am Fahrzeug montieren",
  technology: "Technologie",
  media: "Medien",
  story: "Die Geschichte",
  specifications: "Spezifikationen",
  studio: "Studio",
  lifestyle: "Lifestyle",
  detail: "Detail",
  macro: "Makro",
  material: "Material",
  video: "Video",
  animation: "Animation",
  playVideo: "Video abspielen",
  close: "Schließen",
  back: "Zurück zur Kollektion",
  difficulty: {
    einfach: "Einfach",
    mittel: "Mittel",
    profi: "Werkstatt",
  },
  availability: {
    "in-stock": "Auf Lager",
    "pre-order": "Vorbestellung",
    "sold-out": "Ausverkauft",
  },
  configGroups: {
    color: "Lackierung",
    wheels: "Felgen",
    tyres: "Reifen",
    battery: "Batteriepaket",
    roof: "Dach",
    cargoBox: "Ladefläche",
    seats: "Sitze",
    lighting: "Beleuchtung",
    doors: "Türen",
    windows: "Verglasung",
    performance: "Performance-Paket",
    towHook: "Anhängerkupplung",
    storage: "Stauraum",
  },
} as const;
